// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vjezba.App.Data;

#nullable disable

namespace Vjezba.App.Migrations
{
    [DbContext(typeof(VjezbaDbContext))]
    [Migration("20260504124953_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Vjezba.Model.KategorijaOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KategorijeOpreme");
                });

            modelBuilder.Entity("Vjezba.Model.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("Vjezba.Model.Odrzavanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("IzvrsioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpremaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrajanjeTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IzvrsioId");

                    b.HasIndex("OpremaId");

                    b.ToTable("Odrzavanja");
                });

            modelBuilder.Entity("Vjezba.Model.Proizvodac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proizvodaci");
                });

            modelBuilder.Entity("Vjezba.Model.RadnaOprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumNabave")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventarniBroj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KategorijaOpremeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LokacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProizvodacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaOpremeId");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("ProizvodacId");

                    b.ToTable("RadnaOprema");
                });

            modelBuilder.Entity("Vjezba.Model.Radnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RadnoMjesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("Vjezba.Model.ServisniZahtjev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hitno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpisKvara")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpremaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OpremaId");

                    b.HasIndex("RadnikId");

                    b.ToTable("ServisniZahtjevi");
                });

            modelBuilder.Entity("Vjezba.Model.ZaduzenjeOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumRazduzenja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumZaduzenja")
                        .HasColumnType("TEXT");

                    b.Property<int>("RadnaOpremaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RadnaOpremaId");

                    b.HasIndex("RadnikId");

                    b.ToTable("ZaduzenjaOpreme");
                });

            modelBuilder.Entity("Vjezba.Model.Odrzavanje", b =>
                {
                    b.HasOne("Vjezba.Model.Radnik", "Izvrsio")
                        .WithMany()
                        .HasForeignKey("IzvrsioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vjezba.Model.RadnaOprema", "Oprema")
                        .WithMany("Odrzavanja")
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsio");

                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("Vjezba.Model.RadnaOprema", b =>
                {
                    b.HasOne("Vjezba.Model.KategorijaOpreme", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaOpremeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vjezba.Model.Lokacija", "Lokacija")
                        .WithMany("Oprema")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vjezba.Model.Proizvodac", "Proizvodac")
                        .WithMany()
                        .HasForeignKey("ProizvodacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Lokacija");

                    b.Navigation("Proizvodac");
                });

            modelBuilder.Entity("Vjezba.Model.ServisniZahtjev", b =>
                {
                    b.HasOne("Vjezba.Model.RadnaOprema", "Oprema")
                        .WithMany()
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vjezba.Model.Radnik", null)
                        .WithMany("ServisniZahtjevi")
                        .HasForeignKey("RadnikId");

                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("Vjezba.Model.ZaduzenjeOpreme", b =>
                {
                    b.HasOne("Vjezba.Model.RadnaOprema", "RadnaOprema")
                        .WithMany("Zaduzenja")
                        .HasForeignKey("RadnaOpremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vjezba.Model.Radnik", "Radnik")
                        .WithMany("Zaduzenja")
                        .HasForeignKey("RadnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RadnaOprema");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("Vjezba.Model.Lokacija", b =>
                {
                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("Vjezba.Model.RadnaOprema", b =>
                {
                    b.Navigation("Odrzavanja");

                    b.Navigation("Zaduzenja");
                });

            modelBuilder.Entity("Vjezba.Model.Radnik", b =>
                {
                    b.Navigation("ServisniZahtjevi");

                    b.Navigation("Zaduzenja");
                });
#pragma warning restore 612, 618
        }
    }
}
